### ISSUE TITLE
Syntax around "main" precludes any other methods in the class for C#/Java

### ISSUE THREAD

**Issue by wchoskins** [HighSchoolHacking/GLS#252]
In C# or Java, the main method must exist inside a class. As a result, the GLS "main" keyword generates a class around "main" called "program". Because of this implicit class definition, there's no way to insert anything inside the "program" class outside of the "main" method.

For example, the following does not appear possible to express in GLS:
```csharp
namespace Test
{
	public class Program
	{
		public static void Main()
		{
			DoWork();
		}

		public static void DoWork()
		{
			Console.WriteLine("Hello world!");
		}
	}
}
```

**Comment by JoshuaKGoldberg** [comment]
Thinking about this, I think a good way to capture the user intent is add a `main context start` command describing what this code snippet has as `public class Program`. Within this main context, there should be allowed a new `function start` command to make the equivalent of `public static void DoWork()`.

Scripting languages would have those functions as regular functions. Compiled C#/Java would have them as member methods.
