### ISSUE TITLE
Add Classes

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [HighSchoolHacking/GLS#33]
This will be a large number of commands.
- [x] Starting the class (generics, extensions)
- [x] Constructors
- [ ] Member variables 
  - [x] public/protected/private
  - [x] static 
  - [ ] override
- [ ] Member functions
  - [x] public/protected/private
  - [x] static 
  - [ ] override

Some small notes:
- C# specifies when a member is overridden. Thus, we do too.
- For languages like Python where privacy is a naming convention, calls to members will _require_ specifying the access level. This is annoying but unavoidable.

**Comment by faulda** [comment]
Is there any way to improve having to specify access level? (I assume this means public/protected/private). I feel like that's really inconvenient :P

Initial ideas:
- have a default if none is specified (most calls to classes are probably public, except within the implementation of a class)
- not enforce Python naming conventions and ignore access levels
- keep track of what members have been declared and what access level they are, and automatically grab the access level so the programmer doesn't have to specify (this one means lines will be dependent on each other, which would be a big change)

**Comment by JoshuaKGoldberg** [comment]
> inconvenient
Yes it is!

> default if none is specified
Agreed, let's go with that.

> not enforce Python naming conventions and ignore access levels
It's pretty solidified in the community to add the _s. They've gotta be in there.

> keep track of what members have been declared
> this means lines will be dependent on each other
Yeah, can't do.

**Comment by JoshuaKGoldberg** [comment]
@faulda just to provide some closure on this - I ended up making `public` non-optional. It made the parser more complex, and I've become a fan of requiring explicitness for these kinds of "loose" scenarios.

**Comment by faulda** [comment]
Sounds good!
