### ISSUE TITLE
Keep a running tally of required imports in conversion contexts

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [HighSchoolHacking/GLS#44]
I really don't want this in GLS but it looks necessary. Enums in Python require a `from enum import Enum` on top, and .NET/JVM languages import dictionaries from system.

Conversion contexts will have to keep a tally of required imports and expose an API to commands to add them. To add them, non-exclusive options are:
* Expose a `getImports(): string[]` method
* Take in whether they should be added on top
* Include this in the `file start` command

**Comment by faulda** [comment]
Hmm that is unfortunate. Will we need to delay processing of file start until the full import list is built?

**Comment by JoshuaKGoldberg** [comment]
Maybe if things get extreme... For now it's safe to plop these before any/all lines, so it should be fine to just do 1 and 2.
