### ISSUE TITLE
Switch existing markdown tables to using HTML

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [HighSchoolHacking/GLS#45]

**Comment by faulda** [comment]
- [ ]  lambda body design.md
-[] README.md

**Comment by faulda** [comment]
Lambda body changed in 61bbb5275ac8cced866811059459a52817beb8e9
README changed in d1d18d312729f0a2d37c92a44a7933c2ebff541f

**Comment by faulda** [comment]
Merged in 5136caf210450e39baa572e34d7b4ec5da56ef74
