### ISSUE TITLE
Fix Java package naming problem

### ISSUE THREAD

**Issue by faulda** [HighSchoolHacking/GLS#53]
The problem: Java package names are all lowercase by convention. Class names are all uppercase by convention. The reasoning is to make sure they don't coincide with each other. A class can't have the same name as a package, and the current code will name the class and package the same thing. The file start command will probably need to be modified.

Possible solutions:
- modify file start to automatically lowercase the package name
- add parameter to file start to take a package/namespace name (useful for C# and Java, at least)

**Comment by JoshuaKGoldberg** [comment]
I'm currently working on casing converters as a part of the `classes` branch that will help a lot with this.

**Comment by JoshuaKGoldberg** [comment]
They're added. Food for thought.

**Comment by JoshuaKGoldberg** [comment]
@faulda What naming convention do the prefer? Is it `camelCase` or `period.case` or something different?

**Comment by faulda** [comment]
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

In practice, the reverse Internet domain is only used by larger companies. We should be careful with allowing period-separated package names (which are legal) because a class in package foo.bar may have to be inside a folder named bar that's inside a folder named foo. I don't remember if that's enforced or not.

**Comment by faulda** [comment]
Was this fixed?
