### ISSUE TITLE
Add a `for each` command

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [HighSchoolHacking/GLS#65]
* [ ] Design doc
* [ ] Implementation

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

**Comment by faulda** [comment]
For...of?

**Comment by JoshuaKGoldberg** [comment]
Added a link to the description.

TypeScript is currently listed as the only language that doesn't support looping over values, which is why such a GLS command hasn't been implemented. But, it actually does support for..of.

**Comment by faulda** [comment]
Kinda looks like a foreach loop

**Comment by JoshuaKGoldberg** [comment]
That's exactly what it is.
