### ISSUE TITLE
Possible new casing conversion format

### ISSUE THREAD

**Issue by faulda** [HighSchoolHacking/GLS#70]
General note on the conversions - it seems like most of the cases we're converting follow a common pattern - each one does something like 
 firstword wordseparator  [nextword wordseparator, ...]    lastword 
 We could structure the base converter to follow this format. At that point, each CaseStyle simply becomes a set of properties:
•how to style the first word
•how to style the middle/next words
•how to style the last word
•what the word separator character (if any) is

Under this style, for example:
 PackageUpperCase = style all words upper case, word separator =  . 
 camelCase = style first word lower case, next and last words upper case, word separator none
 etc.

We can consider modifying conversions to follow this pattern, which would make adding new case styles extremely easy - all you need is a couple properties.

**Comment by JoshuaKGoldberg** [comment]
Agreed, I like it.

**Comment by JoshuaKGoldberg** [comment]
Ended up refactoring to be more like this :)
